# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/multi_video.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultiVideoMainWindow(object):
    def setupUi(self, MultiVideoMainWindow):
        MultiVideoMainWindow.setObjectName("MultiVideoMainWindow")
        MultiVideoMainWindow.resize(1177, 474)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MultiVideoMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MultiVideoMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(120)
        self.tableView.horizontalHeader().setMinimumSectionSize(100)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        MultiVideoMainWindow.setCentralWidget(self.centralwidget)
        self.statusBarObj = QtWidgets.QStatusBar(MultiVideoMainWindow)
        self.statusBarObj.setObjectName("statusBarObj")
        MultiVideoMainWindow.setStatusBar(self.statusBarObj)
        self.menuBarObj = QtWidgets.QMenuBar(MultiVideoMainWindow)
        self.menuBarObj.setGeometry(QtCore.QRect(0, 0, 1177, 20))
        self.menuBarObj.setObjectName("menuBarObj")
        self.menuFile = QtWidgets.QMenu(self.menuBarObj)
        self.menuFile.setObjectName("menuFile")
        self.menuVideo = QtWidgets.QMenu(self.menuBarObj)
        self.menuVideo.setObjectName("menuVideo")
        self.menu_Position = QtWidgets.QMenu(self.menuBarObj)
        self.menu_Position.setObjectName("menu_Position")
        MultiVideoMainWindow.setMenuBar(self.menuBarObj)
        self.toolBar = QtWidgets.QToolBar(MultiVideoMainWindow)
        self.toolBar.setObjectName("toolBar")
        MultiVideoMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.actionAdd.setIcon(icon)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.actionDelete.setIcon(icon)
        self.actionDelete.setObjectName("actionDelete")
        self.actionReset = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("document-revert")
        self.actionReset.setIcon(icon)
        self.actionReset.setObjectName("actionReset")
        self.actionLoad = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionFind_Opened = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.actionFind_Opened.setIcon(icon)
        self.actionFind_Opened.setObjectName("actionFind_Opened")
        self.actionSet_Position = QtWidgets.QAction(MultiVideoMainWindow)
        self.actionSet_Position.setCheckable(True)
        icon = QtGui.QIcon.fromTheme("document-page-setup")
        self.actionSet_Position.setIcon(icon)
        self.actionSet_Position.setObjectName("actionSet_Position")
        self.actionStart = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.actionClose = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.actionPause = QtWidgets.QAction(MultiVideoMainWindow)
        self.actionPause.setCheckable(True)
        icon = QtGui.QIcon.fromTheme("media-playback-pause")
        self.actionPause.setIcon(icon)
        self.actionPause.setObjectName("actionPause")
        self.actionSave_As = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_As.setIcon(icon)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAssign = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-fit-best")
        self.actionAssign.setIcon(icon)
        self.actionAssign.setObjectName("actionAssign")
        self.actionMove_Down = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("go-down")
        self.actionMove_Down.setIcon(icon)
        self.actionMove_Down.setObjectName("actionMove_Down")
        self.actionMove_Up = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("go-up")
        self.actionMove_Up.setIcon(icon)
        self.actionMove_Up.setObjectName("actionMove_Up")
        self.actionNew = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionShuffle = QtWidgets.QAction(MultiVideoMainWindow)
        icon = QtGui.QIcon.fromTheme("media-playlist-shuffle")
        self.actionShuffle.setIcon(icon)
        self.actionShuffle.setObjectName("actionShuffle")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset)
        self.menuVideo.addAction(self.actionAdd)
        self.menuVideo.addAction(self.actionDelete)
        self.menuVideo.addAction(self.actionMove_Down)
        self.menuVideo.addAction(self.actionMove_Up)
        self.menuVideo.addAction(self.actionShuffle)
        self.menuVideo.addSeparator()
        self.menuVideo.addAction(self.actionStart)
        self.menuVideo.addAction(self.actionPause)
        self.menuVideo.addAction(self.actionClose)
        self.menu_Position.addAction(self.actionFind_Opened)
        self.menu_Position.addAction(self.actionSet_Position)
        self.menu_Position.addAction(self.actionAssign)
        self.menuBarObj.addAction(self.menuFile.menuAction())
        self.menuBarObj.addAction(self.menuVideo.menuAction())
        self.menuBarObj.addAction(self.menu_Position.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionMove_Down)
        self.toolBar.addAction(self.actionMove_Up)
        self.toolBar.addAction(self.actionShuffle)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFind_Opened)
        self.toolBar.addAction(self.actionSet_Position)
        self.toolBar.addAction(self.actionAssign)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MultiVideoMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MultiVideoMainWindow)

    def retranslateUi(self, MultiVideoMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MultiVideoMainWindow.setWindowTitle(
            _translate("MultiVideoMainWindow", "[*]Multi Video Manager[*]"))
        self.menuFile.setTitle(_translate("MultiVideoMainWindow", "&File"))
        self.menuVideo.setTitle(_translate("MultiVideoMainWindow", "&Video"))
        self.menu_Position.setTitle(_translate("MultiVideoMainWindow", "&Position"))
        self.toolBar.setWindowTitle(_translate("MultiVideoMainWindow", "toolBar"))
        self.actionAdd.setText(_translate("MultiVideoMainWindow", "&Add"))
        self.actionDelete.setText(_translate("MultiVideoMainWindow", "&Delete"))
        self.actionDelete.setShortcut(_translate("MultiVideoMainWindow", "Del"))
        self.actionReset.setText(_translate("MultiVideoMainWindow", "&Reset"))
        self.actionLoad.setText(_translate("MultiVideoMainWindow", "&Open"))
        self.actionLoad.setToolTip(_translate("MultiVideoMainWindow", "Open"))
        self.actionLoad.setShortcut(_translate("MultiVideoMainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MultiVideoMainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MultiVideoMainWindow", "Ctrl+S"))
        self.actionFind_Opened.setText(_translate("MultiVideoMainWindow", "&Find Opened"))
        self.actionFind_Opened.setToolTip(_translate("MultiVideoMainWindow", "Find Opened"))
        self.actionSet_Position.setText(_translate("MultiVideoMainWindow", "&Set Position"))
        self.actionStart.setText(_translate("MultiVideoMainWindow", "&Start"))
        self.actionClose.setText(_translate("MultiVideoMainWindow", "&Close"))
        self.actionClose.setShortcut(_translate("MultiVideoMainWindow", "Ctrl+Esc"))
        self.actionPause.setText(_translate("MultiVideoMainWindow", "&Pause"))
        self.actionPause.setShortcut(_translate("MultiVideoMainWindow", "Space"))
        self.actionSave_As.setText(_translate("MultiVideoMainWindow", "Save &As"))
        self.actionSave_As.setShortcut(_translate("MultiVideoMainWindow", "Ctrl+Shift+S"))
        self.actionAssign.setText(_translate("MultiVideoMainWindow", "&Assign"))
        self.actionAssign.setToolTip(_translate("MultiVideoMainWindow", "Assign"))
        self.actionMove_Down.setText(_translate("MultiVideoMainWindow", "&Move Down"))
        self.actionMove_Up.setText(_translate("MultiVideoMainWindow", "Move &Up"))
        self.actionMove_Up.setToolTip(_translate("MultiVideoMainWindow", "Move Up"))
        self.actionNew.setText(_translate("MultiVideoMainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MultiVideoMainWindow", "Ctrl+N"))
        self.actionShuffle.setText(_translate("MultiVideoMainWindow", "S&huffle"))
